### ISSUE TITLE
Commit access

### ISSUE THREAD

**Issue by kingpong** [fpickle/Stack-It.NET#1]
Frank, will you grant me commit access to this repo?

**Comment by fpickle** [comment]
I'll have to do it tonight.   I'll let you know when it's done.

**Comment by fpickle** [comment]
You should be able to push now.  Let me know if you have any issues.

**Comment by kingpong** [comment]
Thanks.  I'm planning to remove any internal URLs and do a force push (rewrite history) to remove ICA internal details like URLs and Amazon resource names.  /cc @nelsonwellswku

**Comment by nelsonwellswku** [comment]
^^ Oops. I guess I missed... whatever those are... are when I told Frank there wasn't any in there (jackie)

**Comment by kingpong** [comment]
It's cool, just wanted to let you know in case you have outstanding changes that you want to keep. After this push, it'll be difficult to merge those in.
